# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_pb2 as simple__pb2


class DelivererStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MultiplyNumbers = channel.unary_unary(
        '/Deliverer/MultiplyNumbers',
        request_serializer=simple__pb2.MultiplyRequest.SerializeToString,
        response_deserializer=simple__pb2.MultiplyResponse.FromString,
        )


class DelivererServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MultiplyNumbers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DelivererServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MultiplyNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.MultiplyNumbers,
          request_deserializer=simple__pb2.MultiplyRequest.FromString,
          response_serializer=simple__pb2.MultiplyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Deliverer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
