# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x45\n\tDeliverer\x12\x38\n\x0fMultiplyNumbers\x12\x10.MultiplyRequest\x1a\x11.MultiplyResponse\"\x00\x62\x06proto3')
)




_MULTIPLYREQUEST = _descriptor.Descriptor(
  name='MultiplyRequest',
  full_name='MultiplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='MultiplyRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='MultiplyRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=55,
)


_MULTIPLYRESPONSE = _descriptor.Descriptor(
  name='MultiplyResponse',
  full_name='MultiplyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MultiplyResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['MultiplyRequest'] = _MULTIPLYREQUEST
DESCRIPTOR.message_types_by_name['MultiplyResponse'] = _MULTIPLYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiplyRequest = _reflection.GeneratedProtocolMessageType('MultiplyRequest', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLYREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyRequest)
  ))
_sym_db.RegisterMessage(MultiplyRequest)

MultiplyResponse = _reflection.GeneratedProtocolMessageType('MultiplyResponse', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLYRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyResponse)
  ))
_sym_db.RegisterMessage(MultiplyResponse)



_DELIVERER = _descriptor.ServiceDescriptor(
  name='Deliverer',
  full_name='Deliverer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=93,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='MultiplyNumbers',
    full_name='Deliverer.MultiplyNumbers',
    index=0,
    containing_service=None,
    input_type=_MULTIPLYREQUEST,
    output_type=_MULTIPLYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DELIVERER)

DESCRIPTOR.services_by_name['Deliverer'] = _DELIVERER

# @@protoc_insertion_point(module_scope)
