# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"&\n\x0eSumLongRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"!\n\x0fSumLongResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"n\n\x14SumEightLongsRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\x12\t\n\x01\x63\x18\x03 \x01(\x03\x12\t\n\x01\x64\x18\x04 \x01(\x03\x12\t\n\x01\x65\x18\x05 \x01(\x03\x12\t\n\x01\x66\x18\x06 \x01(\x03\x12\t\n\x01g\x18\x07 \x01(\x03\x12\t\n\x01h\x18\x08 \x01(\x03\"\x1a\n\rStringRequest\x12\t\n\x01\x61\x18\x01 \x01(\t\" \n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xf7\x01\n\tDeliverer\x12)\n\nSumNumbers\x12\x0b.SumRequest\x1a\x0c.SumResponse\"\x00\x12\x1f\n\x0bSumOnServer\x12\x06.Empty\x1a\x06.Empty\"\x00\x12.\n\x07SumLong\x12\x0f.SumLongRequest\x1a\x10.SumLongResponse\"\x00\x12:\n\rSumEightLongs\x12\x15.SumEightLongsRequest\x1a\x10.SumLongResponse\"\x00\x12\x32\n\rStringReplace\x12\x0e.StringRequest\x1a\x0f.StringResponse\"\x00\x62\x06proto3')
)




_SUMREQUEST = _descriptor.Descriptor(
  name='SumRequest',
  full_name='SumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='SumRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=50,
)


_SUMRESPONSE = _descriptor.Descriptor(
  name='SumResponse',
  full_name='SumResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SumResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=90,
)


_SUMLONGREQUEST = _descriptor.Descriptor(
  name='SumLongRequest',
  full_name='SumLongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumLongRequest.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='SumLongRequest.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=130,
)


_SUMLONGRESPONSE = _descriptor.Descriptor(
  name='SumLongResponse',
  full_name='SumLongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SumLongResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=165,
)


_SUMEIGHTLONGSREQUEST = _descriptor.Descriptor(
  name='SumEightLongsRequest',
  full_name='SumEightLongsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumEightLongsRequest.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='SumEightLongsRequest.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='SumEightLongsRequest.c', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='SumEightLongsRequest.d', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='SumEightLongsRequest.e', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='SumEightLongsRequest.f', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='g', full_name='SumEightLongsRequest.g', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='SumEightLongsRequest.h', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=277,
)


_STRINGREQUEST = _descriptor.Descriptor(
  name='StringRequest',
  full_name='StringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='StringRequest.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=305,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='StringResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=339,
)

DESCRIPTOR.message_types_by_name['SumRequest'] = _SUMREQUEST
DESCRIPTOR.message_types_by_name['SumResponse'] = _SUMRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SumLongRequest'] = _SUMLONGREQUEST
DESCRIPTOR.message_types_by_name['SumLongResponse'] = _SUMLONGRESPONSE
DESCRIPTOR.message_types_by_name['SumEightLongsRequest'] = _SUMEIGHTLONGSREQUEST
DESCRIPTOR.message_types_by_name['StringRequest'] = _STRINGREQUEST
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumRequest)
  ))
_sym_db.RegisterMessage(SumRequest)

SumResponse = _reflection.GeneratedProtocolMessageType('SumResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUMRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumResponse)
  ))
_sym_db.RegisterMessage(SumResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

SumLongRequest = _reflection.GeneratedProtocolMessageType('SumLongRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMLONGREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumLongRequest)
  ))
_sym_db.RegisterMessage(SumLongRequest)

SumLongResponse = _reflection.GeneratedProtocolMessageType('SumLongResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUMLONGRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumLongResponse)
  ))
_sym_db.RegisterMessage(SumLongResponse)

SumEightLongsRequest = _reflection.GeneratedProtocolMessageType('SumEightLongsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMEIGHTLONGSREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumEightLongsRequest)
  ))
_sym_db.RegisterMessage(SumEightLongsRequest)

StringRequest = _reflection.GeneratedProtocolMessageType('StringRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:StringRequest)
  ))
_sym_db.RegisterMessage(StringRequest)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)



_DELIVERER = _descriptor.ServiceDescriptor(
  name='Deliverer',
  full_name='Deliverer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=342,
  serialized_end=589,
  methods=[
  _descriptor.MethodDescriptor(
    name='SumNumbers',
    full_name='Deliverer.SumNumbers',
    index=0,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SumOnServer',
    full_name='Deliverer.SumOnServer',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SumLong',
    full_name='Deliverer.SumLong',
    index=2,
    containing_service=None,
    input_type=_SUMLONGREQUEST,
    output_type=_SUMLONGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SumEightLongs',
    full_name='Deliverer.SumEightLongs',
    index=3,
    containing_service=None,
    input_type=_SUMEIGHTLONGSREQUEST,
    output_type=_SUMLONGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StringReplace',
    full_name='Deliverer.StringReplace',
    index=4,
    containing_service=None,
    input_type=_STRINGREQUEST,
    output_type=_STRINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DELIVERER)

DESCRIPTOR.services_by_name['Deliverer'] = _DELIVERER

# @@protoc_insertion_point(module_scope)
