# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\"\x07\n\x05\x45mpty\"\x1b\n\x0eSumLongRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\"!\n\x0fSumLongResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"n\n\x14SumEightLongsRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\x12\t\n\x01\x63\x18\x03 \x01(\x03\x12\t\n\x01\x64\x18\x04 \x01(\x03\x12\t\n\x01\x65\x18\x05 \x01(\x03\x12\t\n\x01\x66\x18\x06 \x01(\x03\x12\t\n\x01g\x18\x07 \x01(\x03\x12\t\n\x01h\x18\x08 \x01(\x03\"\x1a\n\rStringRequest\x12\t\n\x01\x61\x18\x01 \x01(\t\" \n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"E\n\x0ePessoaEndereco\x12\x17\n\x06person\x18\x01 \x01(\x0b\x32\x07.Pessoa\x12\x1a\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\t.Endereco\"7\n\x08\x45ndereco\x12\x0e\n\x06\x63idade\x18\x01 \x01(\t\x12\x0b\n\x03rua\x18\x02 \x01(\t\x12\x0e\n\x06numero\x18\x03 \x01(\x05\"%\n\x06Pessoa\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05idade\x18\x02 \x01(\x05\"1\n\x0ePessoaResposta\x12\x11\n\tid_pessoa\x18\x01 \x01(\x05\x12\x0c\n\x04hora\x18\x02 \x01(\t2\xb7\x02\n\tDeliverer\x12 \n\x0cVoidOnServer\x12\x06.Empty\x1a\x06.Empty\"\x00\x12.\n\x07\x44upLong\x12\x0f.SumLongRequest\x1a\x10.SumLongResponse\"\x00\x12:\n\rSumEightLongs\x12\x15.SumEightLongsRequest\x1a\x10.SumLongResponse\"\x00\x12\x32\n\rStringReplace\x12\x0e.StringRequest\x1a\x0f.StringResponse\"\x00\x12<\n\x16\x43omplexObjectOperation\x12\x0f.PessoaEndereco\x1a\x0f.PessoaResposta\"\x00\x12*\n\nAddAddress\x12\t.Endereco\x1a\x0f.PessoaResposta\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_SUMLONGREQUEST = _descriptor.Descriptor(
  name='SumLongRequest',
  full_name='SumLongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumLongRequest.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)


_SUMLONGRESPONSE = _descriptor.Descriptor(
  name='SumLongResponse',
  full_name='SumLongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SumLongResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=87,
)


_SUMEIGHTLONGSREQUEST = _descriptor.Descriptor(
  name='SumEightLongsRequest',
  full_name='SumEightLongsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumEightLongsRequest.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='SumEightLongsRequest.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='SumEightLongsRequest.c', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='SumEightLongsRequest.d', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='SumEightLongsRequest.e', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='SumEightLongsRequest.f', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='g', full_name='SumEightLongsRequest.g', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='SumEightLongsRequest.h', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=199,
)


_STRINGREQUEST = _descriptor.Descriptor(
  name='StringRequest',
  full_name='StringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='StringRequest.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=227,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='StringResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=261,
)


_PESSOAENDERECO = _descriptor.Descriptor(
  name='PessoaEndereco',
  full_name='PessoaEndereco',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='PessoaEndereco.person', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='PessoaEndereco.address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=332,
)


_ENDERECO = _descriptor.Descriptor(
  name='Endereco',
  full_name='Endereco',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cidade', full_name='Endereco.cidade', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rua', full_name='Endereco.rua', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numero', full_name='Endereco.numero', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=389,
)


_PESSOA = _descriptor.Descriptor(
  name='Pessoa',
  full_name='Pessoa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Pessoa.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idade', full_name='Pessoa.idade', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=428,
)


_PESSOARESPOSTA = _descriptor.Descriptor(
  name='PessoaResposta',
  full_name='PessoaResposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_pessoa', full_name='PessoaResposta.id_pessoa', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hora', full_name='PessoaResposta.hora', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=479,
)

_PESSOAENDERECO.fields_by_name['person'].message_type = _PESSOA
_PESSOAENDERECO.fields_by_name['address'].message_type = _ENDERECO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SumLongRequest'] = _SUMLONGREQUEST
DESCRIPTOR.message_types_by_name['SumLongResponse'] = _SUMLONGRESPONSE
DESCRIPTOR.message_types_by_name['SumEightLongsRequest'] = _SUMEIGHTLONGSREQUEST
DESCRIPTOR.message_types_by_name['StringRequest'] = _STRINGREQUEST
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['PessoaEndereco'] = _PESSOAENDERECO
DESCRIPTOR.message_types_by_name['Endereco'] = _ENDERECO
DESCRIPTOR.message_types_by_name['Pessoa'] = _PESSOA
DESCRIPTOR.message_types_by_name['PessoaResposta'] = _PESSOARESPOSTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

SumLongRequest = _reflection.GeneratedProtocolMessageType('SumLongRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMLONGREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumLongRequest)
  ))
_sym_db.RegisterMessage(SumLongRequest)

SumLongResponse = _reflection.GeneratedProtocolMessageType('SumLongResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUMLONGRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumLongResponse)
  ))
_sym_db.RegisterMessage(SumLongResponse)

SumEightLongsRequest = _reflection.GeneratedProtocolMessageType('SumEightLongsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMEIGHTLONGSREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SumEightLongsRequest)
  ))
_sym_db.RegisterMessage(SumEightLongsRequest)

StringRequest = _reflection.GeneratedProtocolMessageType('StringRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:StringRequest)
  ))
_sym_db.RegisterMessage(StringRequest)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)

PessoaEndereco = _reflection.GeneratedProtocolMessageType('PessoaEndereco', (_message.Message,), dict(
  DESCRIPTOR = _PESSOAENDERECO,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:PessoaEndereco)
  ))
_sym_db.RegisterMessage(PessoaEndereco)

Endereco = _reflection.GeneratedProtocolMessageType('Endereco', (_message.Message,), dict(
  DESCRIPTOR = _ENDERECO,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Endereco)
  ))
_sym_db.RegisterMessage(Endereco)

Pessoa = _reflection.GeneratedProtocolMessageType('Pessoa', (_message.Message,), dict(
  DESCRIPTOR = _PESSOA,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Pessoa)
  ))
_sym_db.RegisterMessage(Pessoa)

PessoaResposta = _reflection.GeneratedProtocolMessageType('PessoaResposta', (_message.Message,), dict(
  DESCRIPTOR = _PESSOARESPOSTA,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:PessoaResposta)
  ))
_sym_db.RegisterMessage(PessoaResposta)



_DELIVERER = _descriptor.ServiceDescriptor(
  name='Deliverer',
  full_name='Deliverer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=482,
  serialized_end=793,
  methods=[
  _descriptor.MethodDescriptor(
    name='VoidOnServer',
    full_name='Deliverer.VoidOnServer',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DupLong',
    full_name='Deliverer.DupLong',
    index=1,
    containing_service=None,
    input_type=_SUMLONGREQUEST,
    output_type=_SUMLONGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SumEightLongs',
    full_name='Deliverer.SumEightLongs',
    index=2,
    containing_service=None,
    input_type=_SUMEIGHTLONGSREQUEST,
    output_type=_SUMLONGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StringReplace',
    full_name='Deliverer.StringReplace',
    index=3,
    containing_service=None,
    input_type=_STRINGREQUEST,
    output_type=_STRINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ComplexObjectOperation',
    full_name='Deliverer.ComplexObjectOperation',
    index=4,
    containing_service=None,
    input_type=_PESSOAENDERECO,
    output_type=_PESSOARESPOSTA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddAddress',
    full_name='Deliverer.AddAddress',
    index=5,
    containing_service=None,
    input_type=_ENDERECO,
    output_type=_PESSOARESPOSTA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DELIVERER)

DESCRIPTOR.services_by_name['Deliverer'] = _DELIVERER

# @@protoc_insertion_point(module_scope)
