# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_pb2 as simple__pb2


class DelivererStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.void_function = channel.unary_unary(
        '/Deliverer/void_function',
        request_serializer=simple__pb2.Empty.SerializeToString,
        response_deserializer=simple__pb2.Empty.FromString,
        )
    self.duplicate_function = channel.unary_unary(
        '/Deliverer/duplicate_function',
        request_serializer=simple__pb2.SumLongRequest.SerializeToString,
        response_deserializer=simple__pb2.SumLongResponse.FromString,
        )
    self.adder_function = channel.unary_unary(
        '/Deliverer/adder_function',
        request_serializer=simple__pb2.SumEightLongsRequest.SerializeToString,
        response_deserializer=simple__pb2.SumLongResponse.FromString,
        )
    self.maximizeString_function = channel.unary_unary(
        '/Deliverer/maximizeString_function',
        request_serializer=simple__pb2.StringRequest.SerializeToString,
        response_deserializer=simple__pb2.StringResponse.FromString,
        )
    self.criaPessoa = channel.unary_unary(
        '/Deliverer/criaPessoa',
        request_serializer=simple__pb2.PessoaEndereco.SerializeToString,
        response_deserializer=simple__pb2.PessoaResposta.FromString,
        )
    self.adicionaEndereco = channel.unary_unary(
        '/Deliverer/adicionaEndereco',
        request_serializer=simple__pb2.Endereco.SerializeToString,
        response_deserializer=simple__pb2.PessoaResposta.FromString,
        )


class DelivererServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def void_function(self, request, context):
    """1)
    operação sem parâmetros e sem valor de retorno
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def duplicate_function(self, request, context):
    """2)
    operação com um long de parâmetro e retorna um long
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def adder_function(self, request, context):
    """3)
    operação com um 8 valores long de parâmetro e retorna um long
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def maximizeString_function(self, request, context):
    """4)
    operação com parâmetro string e valor de retorno string
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def criaPessoa(self, request, context):
    """5) Operação que passa um tipo complexo e retorna outro tipo complexo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def adicionaEndereco(self, request, context):
    """Insere um endereço no banco de dados e retorna seu id e uma data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DelivererServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'void_function': grpc.unary_unary_rpc_method_handler(
          servicer.void_function,
          request_deserializer=simple__pb2.Empty.FromString,
          response_serializer=simple__pb2.Empty.SerializeToString,
      ),
      'duplicate_function': grpc.unary_unary_rpc_method_handler(
          servicer.duplicate_function,
          request_deserializer=simple__pb2.SumLongRequest.FromString,
          response_serializer=simple__pb2.SumLongResponse.SerializeToString,
      ),
      'adder_function': grpc.unary_unary_rpc_method_handler(
          servicer.adder_function,
          request_deserializer=simple__pb2.SumEightLongsRequest.FromString,
          response_serializer=simple__pb2.SumLongResponse.SerializeToString,
      ),
      'maximizeString_function': grpc.unary_unary_rpc_method_handler(
          servicer.maximizeString_function,
          request_deserializer=simple__pb2.StringRequest.FromString,
          response_serializer=simple__pb2.StringResponse.SerializeToString,
      ),
      'criaPessoa': grpc.unary_unary_rpc_method_handler(
          servicer.criaPessoa,
          request_deserializer=simple__pb2.PessoaEndereco.FromString,
          response_serializer=simple__pb2.PessoaResposta.SerializeToString,
      ),
      'adicionaEndereco': grpc.unary_unary_rpc_method_handler(
          servicer.adicionaEndereco,
          request_deserializer=simple__pb2.Endereco.FromString,
          response_serializer=simple__pb2.PessoaResposta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Deliverer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
